/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Begin": "开始",
    "Note that the game may be paused in the settings, this might be helpful...": "请注意，游戏可以在设置中暂停，这可能会有所帮助…",
    "You were sent to jail for tax evasion and need to escape.": "你因逃税被送进了地牢，你需要逃离。",
    "Logs": "日志",
    "Actions": "行动",
    "Main": "首页",
    "Resources": "资源",
    "Upgrades": "升级",
    "What even is this place?": "这到底是什么地方？",
    "Wake up": "醒来",
    "Ughhhh that didn't feel good...": "呃，感觉不太好...",
    "(currently active)": "(当前活跃)",
    "Rest": "休息",
    "That felt better": "感觉好多了",
    "You seem to be in a jail.": "你似乎在一个地牢里面。",
    "Gain some energy and clear your head": "获得一些能量，让你的头脑清醒",
    "A game made for the": "本游戏的制作是为了参加",
    "Buy a candy bar from the prison shop.": "从地牢商店买块糖果。",
    "Buy a shovel to help you find more junk.": "买一把铲子来帮你找到更多的垃圾。",
    "Candy bars": "糖果棒",
    "Crowbar": "撬棍",
    "Eat": "吃",
    "Work": "工作",
    "Work in the jail for some money, but use energy": "在地牢里工作挣钱，但要消耗能量",
    "Wipe Save": "擦除存档",
    "Wait for prison guards to give you some food": "等着地牢看守给你食物",
    "Toolmaking": "工具制造",
    "That felt better...": "感觉好多了...",
    "Summer Incremental Game Jam 2024": "Summer Incremental Game Jam 2024",
    "Shovel": "铲子",
    "Research": "研究",
    "Rest to gain energy, using up your Total Energy.": "休息来获取能量，消耗你的全部能量。",
    "Pernamently unlock Research.": "永久解锁研究",
    "Pause the game (or press \"p\")": "暂停游戏（或按“p”键）",
    "Make some tools using junk, which should help improve your Work quality.": "用垃圾做一些工具，这应该有助于提高你的工作质量。",
    "Make a crowbar out of junk.": "用垃圾做个撬棍。",
    "Jail Evasion Incremental": "地牢逃离增量",
    "Import from File": "从文件导入",
    "Find some junk around here": "在这附近找些垃圾",
    "Find junk": "寻找垃圾",
    "Export as file": "导出为文件",
    "Upgrade Effects": "升级效果",
    "Action Effects": "行动效果",
    "Need energy": "需要能量",
    "Destruction": "破坏",
    "Create a big enough hole so that you can escape.": "挖一个足够大的洞，这样你就能逃出去了。",
    "Bribe one of your jail cell guards": "贿赂你的地牢看守",
    "Bribery": "贿赂",
    "Buy a book on the secrets of doing more in less time.": "买一本关于如何用更少的时间做更多事情的书。",
    "Efficency": "效率",
    "Jars": "罐子",
    "Somehow no one noticed...?": "不知怎么没人注意到...？",
    "Use jars to preserve food.": "用罐子保存食物。",
    "You can buy more powerful and useful upgrades here.": "你可以在这里购买更强大和有用的升级。",
    "Escape": "逃离",
    "It's kind of tiring though": "虽然有点累",
    "Quit": "退出",
    "The Door": "门",
    "Run to the exit to escape. You might need energy for after the escape however...": "跑到出口逃跑。然而，你可能需要能量来逃生。",
    "The door that blocks your path to the outside isn't movable, so you'll need to pry it open.": "阻挡你通往外面的门是不能移动的，所以你需要撬开它。",
    "The exit seems to be guarded by a pin pad...": "出口处好像有个密码板把守着...",
    "Try to get the door open": "试着把门打开",
    "Whenever the yellow area is in the green area, you can pry it open partially. You'll need to do this 5 times in order to get the door open enough to escape. However, if the yellow area isn't in the green area and you attempt to pry it, all of your progress will be reset. Note that you can also press the space bar to pry as well.": "当黄色区域位于绿色区域时，您可以将其部分撬开。你需要这样做5次才能打开足够的门逃跑。但是，如果黄色区域不在绿色区域，并且你试图撬开它，你的所有进程将被重置。请注意，您也可以按空格键来撬。",
    "You have no idea why that worked, but now you can escape!": "你不知道为什么会成功，但现在你可以逃脱了！",
    "Bribe police so they won't be after you as much.": "贿赂捕快，这样他们就不会对你穷追不舍了。",
    "Explore": "探索",
    "Job Bonus": "工作加成",
    "Is this even a good idea?": "这是个好主意吗？",
    "Learning": "学习",
    "Look around for some opportunities.": "看看周围有没有机会。",
    "Might be risky though...": "不过可能有风险...",
    "The police are after you! This bar represents how close they are to finding you. If the bar ever reaches 0%, you will be sent back to jail again. Evasion loss doubles every 30 seconds.": "捕快在追你！这个条代表他们离找到你有多近。如果分数达到0%，你将再次被送回地牢。躲避损失每30秒翻倍。",
    "Use your experience on the job to get a bonus!": "用你的工作经验来获得加成！",
    "Use your experience to gain extra cash.": "用你的经验来赚取额外的钱。",
    "Work and get money along with some experience": "去工作，在获得一些经验的同时赚钱",
    "XP that you have.": "你所拥有的经验值。",
    "You escaped the jail!  Better get going though, they'll be looking for you soon.": "你从地牢逃出来了！最好还是走吧，他们很快就会来找你的。",
    "Experienced": "经验丰富",
    "Energy, used for performing actions. Obtained through resting.": "能量，用于执行行动。通过休息获得的",
    "Metal Detectors": "金属探测器",
    "Reset": "重置",
    "Note that due to the nature of Research upgrades, they are PERNAMENT and are kept across jail.": "请注意，由于研究升级的性质，它们是永久的，并且被保存在地牢中。",
    "Repair some metal detectors that you found to get more junk.": "修理一些你发现的金属探测器，以获得更多的垃圾。",
    "You'll need money if you want to have a chance at escaping.": "如果你想有机会逃跑，你需要钱。",
    "Use your experience to get more experience!": "利用你的经验来获得更多的经验！",
    "Sneakier": "潜行者",
    "Use your experience with the environment around you to increase the Evasion cap.": "利用你的经验和你周围的环境来增加逃避上限。",
    "Use your experience with the police to divide Evasion loss.": "用你和捕快打交道的经验来分摊逃避损失。",
    "Use your experience to increase Action speed.": "使用你的经验值来提高行动速度。",
    "Use your experience from past jailbreak attempts to make your next attempt better.": "利用你过去的越狱经验，让你下次的越狱尝试变得更好。",
    "Speed": "速度",
    "Sneaky": "偷偷摸摸",
    "Junk that you found in the prison. Could be useful...": "你在地牢里找到的垃圾。可能有用...",
    "The door is still weak from the time you tried to pry it open, meaning it wasn't too difficult getting out of there.": "从你试图撬开它的时候起，门还是很脆弱，这意味着从那里出去并不太难。",
    "The police caught up to you and sent you back to jail again. :( Better luck next time...": "捕快抓住了你，又把你送回了地牢。祝你下次好运...",
    "You escaped the jail! Better get going though, they'll be looking for you soon.": "你从地牢逃出来了！最好还是走吧，他们很快就会来找你的。",
    "Import your save.": "导入你的存档。",
    "Experience you've gained through previous jailbreak attempts.": "你通过以前的越狱尝试获得的经验。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Effect: ": "效果: ",
    "Requirement: $": "需要: $",
    "Requirement: ": "需要: ",
    "You got $": "你得到了 $",
    "Pry (": "撬 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " Total Energy": " 总能量",
    ") Experience": ") 经验",
    "/sec) Evasion": "/秒) 躲避",
    "/sec) XP": "/秒) 经验",
    "/sec) / 100 Energy": "/秒) / 100 能量",
    " to Work cash gain": " 到工作现金增益",
    " to Action speed": " 到行动速度",
    " to Evasion loss": " 到逃避丢失",
    " to junk gain": " 到垃圾增益",
    " to Junk gain": " 到垃圾增益",
    " to Experience gain": " 到经验值增益",
    " to all gain": " 到所有增益",
    " to Total Energy (retroactive)": " 到总能量（追溯）",
    " Energy/sec": " 能量/秒",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.]+)\% \/ ([\d\.,]+)\%$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+).$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) \(\-([\d\.]+)$/,
    /^\$([\d\.,]+) \(\+([\d\.]+)$/,
    /^([\d\.,]+) \(\-([\d\.,]+)$/,
    /^([\d\.,]+) \(\+([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You currently have (.+) Experience, increased by Cash.$/, '你现在的经验值是 $1，通过现金增加。'],
    [/^Start over for (.+) Experience.$/, '重新开始以获得 $1 经验值。'],
    [/^You found (.+) junk.$/, '你找到 $1 垃圾。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) Experience$/, '$1 经验值'],
    [/^([\d\.]+) junk$/, '$1 垃圾'],
    [/^×([\d\.]+) Evasion Loss$/, '×$1 逃离损失'],
    [/^([\d\.]+) Experience and ([\d\.]+) junk$/, '$1 经验值和 $2 垃圾'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) XP$/, '$1 经验值'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) free$/, '$1 空闲'],
    [/^([\d\.,]+) Junk$/, '$1 垃圾'],
    [/^([\d\.,]+) and ([\d\.,]+) Junk \(not spent\)$/, '$1 和 $2 垃圾（未花费）'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);